#region Copyright
/*******************************************************************************
 * NerdyDuck.Collections - Validation and serialization of parameter values
 * 
 * The MIT License (MIT)
 *
 * Copyright (c) Daniel Kopp, dak@nerdyduck.de
 *
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 ******************************************************************************/
#endregion

namespace NerdyDuck.ParameterValidation;

/// <summary>
/// Error codes for the NerdyDuck.ParameterValidation assembly.
/// </summary>
internal enum ErrorCodes
{
	None = 0x0000,
	TypeExtensions_ToStringAssemblyNameOnly_ArgNull,
	Constraint_ctor_ArgNull,
	Constraint_Validate_TypeNone,
	Constraint_SetParameters_TypeNone,
	Constraint_SetParameters_ParametersNull,
	Constraint_AssertDataType_TypeNotSupported,
	FileNameConstraint_Validate_ValueNullEmpty,
	FileNameConstraint_Validate_ValueInvalid,
	PathConstraint_Validate_ValueEmpty,
	PathConstraint_Validate_ValueInvalid,
	LowerCaseConstraint_Validate_ValueInvalid,
	UpperCaseConstraint_Validate_ValueInvalid,
	AllowedSchemeConstraint_ctor_StringNullEmpty,
	AllowedSchemeConstraint_ctor_EnumNull,
	AllowedSchemeConstraint_CheckSchemes_NoSchemes,
	AllowedSchemeConstraint_CheckSchemes_SchemeNullEmpty,
	AllowedSchemeConstraint_Validate_SchemeNotAllowed,
	CharacterSetConstraint_SetParameters_OnlyOneParam,
	CharacterSetConstraint_SetParameters_CharSetInvalid,
	CharacterSetConstraint_Validate_CharNotDefined,
	MaximumValueConstraint_ctor_MaxValueNull,
	ParameterConvert_NetToParameterDataType_ArgNull,
	ParameterConvert_NetToParameterDataType_TypeNotSupported,
	ParameterConvert_ParameterToNetDataType_NoMatch,
	MaximumValueConstraint_Validate_TooLarge,
	MaximumValueConstraint_SetParameters_OnlyOneParam,
	MaximumValueConstraint_SetParameters_ParamInvalid,
	MaximumValueConstraint_CheckDataType_TypeNotSupported,
	MaximumValueConstraint_Validate_TypeMismatch,
	MaximumValueConstraint_CheckValueType_TypeMismatch,
	MinimumValueConstraint_ctor_MinValueNull,
	MinimumValueConstraint_SetParameters_ParamInvalid,
	MinimumValueConstraint_Validate_TooSmall,
	MinimumValueConstraint_SetParameters_OnlyOneParam,
	MinimumValueConstraint_Validate_TypeMismatch,
	MinimumValueConstraint_CheckDataType_TypeNotSupported,
	MinimumValueConstraint_CheckValueType_TypeMismatch,
	StepConstraint_ctor_StepSizeNull,
	StepConstraint_SetParameters_OnlyOneParam,
	StepConstraint_SetParameters_ParamInvalid,
	StepConstraint_CheckDataType_TypeNotSupported,
	StepConstraint_CheckValueType_TypeMismatch,
	DecimalPlacesConstraint_SetParameters_OnlyOneParam,
	DecimalPlacesConstraint_SetParameters_ParamInvalid,
	LengthConstraint_ctor_LengthNegative,
	MaximumLengthConstraint_ctor_LengthNegative,
	MinimumLengthConstraint_ctor_LengthNegative,
	LengthConstraint_SetParameters_OnlyOneParam,
	MaximumLengthConstraint_SetParameters_OnlyOneParam,
	MinimumLengthConstraint_SetParameters_OnlyOneParam,
	LengthConstraint_SetParameters_LengthNegative,
	MaximumLengthConstraint_SetParameters_LengthNegative,
	MinimumLengthConstraint_SetParameters_LengthNegative,
	LengthConstraint_SetParameters_ParamInvalid,
	MaximumLengthConstraint_SetParameters_ParamInvalid,
	MinimumLengthConstraint_SetParameters_ParamInvalid,
	LengthConstraint_Validate_TypeNotSupported,
	MaximumLengthConstraint_Validate_TypeNotSupported,
	MinimumLengthConstraint_Validate_TypeNotSupported,
	LengthConstraint_Validate_LengthInvalid,
	MaximumLengthConstraint_Validate_TooLong,
	MinimumLengthConstraint_Validate_TooShort,
	RegexConstraint_ctor_StringNullEmpty,
	RegexConstraint_ctor_OptionsInvalid,
	RegexConstraint_ctor_RegexInvalid,
	RegexConstraint_SetParameters_OneParam,
	RegexConstraint_SetParameters_RegexInvalid,
	RegexConstraint_SetParameters_OptionsInvalid,
	RegexConstraint_Validate_NoMatch,
	TypeConstraint_ctor_TypeNullEmpty,
	TypeConstraint_SetParameters_TypeNullEmpty,
	EnumTypeConstraint_Validate_WrongEnum,
	EnumValuesConstraint_ctor_NotInteger,
	EnumValuesConstraint_ctor_ValuesNull,
	EnumValuesConstraint_ctor_ValuesTypeMismatch,
	EnumValuesConstraint_SetParameters_InvalidDataType,
	EnumValuesConstraint_SetParameters_NoValues,
	EnumValuesConstraint_SetParameters_ValuePairInvalid,
	EnumValuesConstraint_SetParameters_KeyInvalid,
	EnumValuesConstraint_SetParameters_DataTypeMismatch,
	EnumValuesConstraint_Validate_NotSetUp,
	EnumValuesConstraint_Validate_InvalidFlag,
	EnumTypeConstraint_Validate_InvalidFlag,
	EnumValuesConstraint_Validate_NotInEnum,
	EnumTypeConstraint_Validate_NotInEnum,
	EnumValuesConstraint_Validate_TypeNotSupported,
	EnumTypeConstraint_Validate_TypeNotSupported,
	ParameterConvert_Encrypt_Failed,
	ParameterConvert_Decrypt_Failed,
	ParameterConvert_ToBoolean_ValueNull,
	ParameterConvert_ToBoolean_ParseFailed,
	ParameterConvert_ToByte_ValueNull,
	ParameterConvert_ToByte_ParseFailed,
	ParameterConvert_ToByteArray_ValueNull,
	ParameterConvert_ToByteArray_ParseFailed,
	ParameterConvert_ToDateTimeOffset_ValueNull,
	ParameterConvert_ToDateTimeOffset_ParseFailed,
	ParameterConvert_ToDecimal_ValueNull,
	ParameterConvert_ToDecimal_ParseFailed,
	ParameterConvert_ToEnumeration_EnumTypeNull,
	ParameterConvert_ToEnumeration_NotEnum,
	ParameterConvert_ToEnumeration_ValueNull,
	ParameterConvert_ToEnumeration_ParseFailed,
	ParameterConvert_ToGuid_ValueNull,
	ParameterConvert_ToGuid_ParseFailed,
	ParameterConvert_ToInt16_ValueNull,
	ParameterConvert_ToInt16_ParseFailed,
	ParameterConvert_ToInt32_ValueNull,
	ParameterConvert_ToInt32_ParseFailed,
	ParameterConvert_ToInt64_ValueNull,
	ParameterConvert_ToInt64_ParseFailed,
	ParameterConvert_ToTimeSpan_ValueNull,
	ParameterConvert_ToTimeSpan_ParseFailed,
	ParameterConvert_ToUInt16_ValueNull,
	ParameterConvert_ToUInt16_ParseFailed,
	ParameterConvert_ToUInt32_ValueNull,
	ParameterConvert_ToUInt32_ParseFailed,
	ParameterConvert_ToUInt64_ValueNull,
	ParameterConvert_ToUInt64_ParseFailed,
	ParameterConvert_ToUri_ValueNull,
	ParameterConvert_ToUri_ParseFailed,
	ParameterConvert_ToVersion_ValueNull,
	ParameterConvert_ToVersion_ParseFailed,
	ParameterConvert_ToSByte_ValueNull,
	ParameterConvert_ToSByte_ParseFailed,
	ParameterConvert_ToString_TypeNotSupported,
	ParameterConvert_ToString_TypeMismatch,
	ParameterConvert_ToDataType_EnumNoTypeConstraint,
	ParameterConvert_ToDataType_ResolveEnumFailed,
	ParameterConvert_ToDataType_XmlNoTypeConstraint,
	ParameterConvert_ToDataType_ResolveXmlFailed,
	ParameterConvert_ToDataType_TypeNotSupported,
	ParameterConvert_FromXml_ValueNull,
	ParameterConvert_FromXml_TypeNull,
	ParameterConvert_FromXml_ParseFailed,
	ParameterConvert_ToXml_SerializeFailed,
	HostNameConstraint_Validate_ValueEmpty,
	HostnameConstraint_Validate_NotHostOrIP,
	EndpointConstraint_Validate_ValueEmpty,
	EndpointConstraint_Validate_NotHostOrIP,
	EndpointConstraint_Validate_PortInvalid,
	ConstraintParser_HandleInConstraint_EmptyConstraint,
	ConstraintParser_CreateConstraint_ParamInvalid,
	ConstraintParser_Parse_DataTypeNone,
	ConstraintParser_HandleInConstraint_InvalidChar,
	ConstraintParser_HandleOutsideConstraint_DataOutside,
	ConstraintParser_HandleInParameters_ParamCharInvalid,
	ConstraintParser_HandleInParameter_ParamUnmaskedChar,
	ConstraintParser_HandleAfterParameter_CharAfterParam,
	ConstraintParser_HandleUnknownConstraint_UnknownConstraint,
	ConstraintParser_HandleUnknownConstraint_NotDefinedForType,
	Constraint_Validate_NameNullEmpty,
	Constraint_GetParameters_ArgNull,
	ParameterValidator_Validate_ValidationFailed,
	ConstraintAttribute_ctor_ConstraintsNullEmpty,
	ConstraintAttribute_ctor_DataTypeNone,
	ParameterValidator_GetValidationResult_DataTypeNone,
	ParameterValidator_GetValidationResult_NameNullEmpty,
	ParameterValidator_GetValidationResult_ValueNull,
	Constraint_GetObjectData_InfoNull,
	Constraint_AssertDataType_TypesNull,
	ConstraintParser_HandleAfterParameters_CharAfterParams,
	ParameterValidationResult_GetObjectData_InfoNull,
	Constraint_OnValidation_ResultsNull,
	Constraint_OnValidation_ValueNull,
	ConstraintParser_Parse_IncompleteConstraint,
	ParameterValidationResult_ctor_ResultNull,
	DisplayHintConstraint_ctor_ArgNullEmpty,
	DisplayHintConstraint_ctor_ArgNull,
	DisplayHintConstraint_CheckParameters_NoParams,
	DisplayHintConstraint_CheckParameters_ParamNullEmpty,
	ParameterConvert_ExamineEnumeration_TypeNull,
	ParameterConvert_ExamineEnumeration_NotEnum,
	DatabaseConstraint_SetParameters_ParamCountInvalid,
	EnumTypeConstraint_SetParameters_OnlyOneParam,
	EnumTypeConstraint_SetParameters_ParamNullEmpty,
	EnumValuesConstraint_SetParameters_ParamCountInvalid,
	TypeConstraint_SetParameters_OnlyOneParam,
	Constraint_ctor_InfoNull,
	ParameterValidationErrorEventArgs_ctor_ResultsNull,
	ParameterConvert_AES_NoAssemblyName,
	ParameterConvert_FromXml_NoObjectDeserialized,
	Constraint_Validate_ValueNull,
	Constraint_OnValidate_NameNullEmpty,
	Constraint_ctor_NameNull,
	InvalidDataTypeException_ctor_DataTypeNull,
	ParameterConversionException_ctor_DataTypeNull,
	ParameterConversionException_ctor_ActualTypeNull,
	ParameterValidationResult_ctor_infoNull,
	AllowedSchemeConstraint_ctor_AllowedSchemesNull,
	CharacterSetConstraint_ctor_CharacterSetNull,
	CharacterSetConstraint_Validate_NotString,
	ParameterConvert_ToString_UnknownEnumType,
	ParameterConvert_ExamineEnumeration_UnknownType,
	ParameterConvert_ToDataType_ValueNull,
	ParameterConvert_ExamineEnumeration_NoFieldValue,
	EnumValuesConstraint_ctor_NoUnderlyingDataType,
	EnumValuesConstraint_ctor_KeyMissing,
	EnumValuesConstraint_ctor_ValueMissing,
	EnumValuesConstraint_GetParameters_DataType,
	EnumValuesConstraint_Validate_ValueType,
	RegexConstraint_ctor_NoOptions,
	RegexConstraint_ctor_NoRegex,
	RegexConstraint_GetParameters_Options,
	StepConstraint_ctor_DataType,
	StepConstraint_ctor_StepSize,
	TypeConstraint_ctor_TypeName,
	MaximumValuesConstraint_ctor_DataType,
	MinimumValueConstraint_ctor_DataType,
	MinimumValueConstraint_ctor_MinimumValue,
	MaximumValueConstraint_ctor_MaximumValue
}
