#region Copyright
/*******************************************************************************
 * NerdyDuck.Collections - Validation and serialization of parameter values
 * 
 * The MIT License (MIT)
 *
 * Copyright (c) Daniel Kopp, dak@nerdyduck.de
 *
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 ******************************************************************************/
#endregion

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

#if NETSTD20
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.AllowedSchemeConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.AllowedSchemeConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.AllowedSchemeConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.AllowedSchemeConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.CharacterSetConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.CharacterSetConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.CharacterSetConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.CharacterSetConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DatabaseConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DatabaseConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DatabaseConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DecimalPlacesConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DecimalPlacesConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DecimalPlacesConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DisplayHintConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DisplayHintConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.DisplayHintConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.EndpointConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.EnumTypeConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.EnumValuesConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.EnumValuesConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.EnumValuesConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.EnumValuesConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.FileNameConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.HostNameConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.LengthConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.LengthConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.LengthConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.LengthConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.LowercaseConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumLengthConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumLengthConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumLengthConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumLengthConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumValueConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumValueConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumValueConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MaximumValueConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumLengthConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumLengthConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumLengthConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumLengthConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumValueConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumValueConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumValueConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.MinimumValueConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.PathConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.RegexConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.RegexConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.RegexConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.RegexConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.StepConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.StepConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.StepConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.TypeConstraint.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.TypeConstraint.GetParameters(System.Collections.Generic.IList{System.String})")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.TypeConstraint.SetParameters(System.Collections.Generic.IReadOnlyList{System.String},NerdyDuck.ParameterValidation.ParameterDataType)")]
[assembly: SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:NerdyDuck.ParameterValidation.Constraints.UppercaseConstraint.OnValidation(System.Collections.Generic.IList{NerdyDuck.ParameterValidation.ParameterValidationResult},System.Object,NerdyDuck.ParameterValidation.ParameterDataType,System.String,System.String)")]
#endif
