//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdyDuck.ParameterValidation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NerdyDuck.ParameterValidation.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the specified scheme strings is null or empty or contains only white-space..
        /// </summary>
        internal static string AllowedSchemeConstraint_CheckSchemes_InvalidScheme {
            get {
                return ResourceManager.GetString("AllowedSchemeConstraint_CheckSchemes_InvalidScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of allowed schemes is empty..
        /// </summary>
        internal static string AllowedSchemeConstraint_CheckSchemes_NoScheme {
            get {
                return ResourceManager.GetString("AllowedSchemeConstraint_CheckSchemes_NoScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized AllowedSchemeConstraint has no AllowedSchemes property..
        /// </summary>
        internal static string AllowedSchemeConstraint_ctor_AllowedSchemesNull {
            get {
                return ResourceManager.GetString("AllowedSchemeConstraint_ctor_AllowedSchemesNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: URI scheme &apos;{1}&apos; is not supported. Allowed schemes: {2}..
        /// </summary>
        internal static string AllowedSchemeConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("AllowedSchemeConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No allowed schemes set..
        /// </summary>
        internal static string AllowedSchemeConstraint_Validate_NotConfigured {
            get {
                return ResourceManager.GetString("AllowedSchemeConstraint_Validate_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASCII.
        /// </summary>
        internal static string CharacterSetConstraint_CharSet_Ascii {
            get {
                return ResourceManager.GetString("CharacterSetConstraint_CharSet_Ascii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-646-IRV Odette Subset.
        /// </summary>
        internal static string CharacterSetConstraint_CharSet_Iso646Odette {
            get {
                return ResourceManager.GetString("CharacterSetConstraint_CharSet_Iso646Odette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO 8859-1.
        /// </summary>
        internal static string CharacterSetConstraint_CharSet_Iso8859 {
            get {
                return ResourceManager.GetString("CharacterSetConstraint_CharSet_Iso8859", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows-1252.
        /// </summary>
        internal static string CharacterSetConstraint_CharSet_Windows1252 {
            get {
                return ResourceManager.GetString("CharacterSetConstraint_CharSet_Windows1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized CharacterSetConstraint has no CharacterSet property..
        /// </summary>
        internal static string CharacterSetConstraint_ctor_CharacterSetNull {
            get {
                return ResourceManager.GetString("CharacterSetConstraint_ctor_CharacterSetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter value &apos;{0}&apos; is not a valid supported character set..
        /// </summary>
        internal static string CharacterSetConstraint_SetParameters_InvalidValue {
            get {
                return ResourceManager.GetString("CharacterSetConstraint_SetParameters_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains at least one character not defined in the {1} character set..
        /// </summary>
        internal static string CharacterSetConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("CharacterSetConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized Constraint contains no Name property..
        /// </summary>
        internal static string Constraint_ctor_NameNull {
            get {
                return ResourceManager.GetString("Constraint_ctor_NameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot configure constraint..
        /// </summary>
        internal static string ConstraintConfigurationException_Message {
            get {
                return ResourceManager.GetString("ConstraintConfigurationException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint &apos;{0}&apos; is not defined for data type &apos;{1}&apos;..
        /// </summary>
        internal static string ConstraintParser_HandleUnknownConstraint_NotDefined {
            get {
                return ResourceManager.GetString("ConstraintParser_HandleUnknownConstraint_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown constraint name &apos;{0}&apos;..
        /// </summary>
        internal static string ConstraintParser_HandleUnknownConstraint_UnknownName {
            get {
                return ResourceManager.GetString("ConstraintParser_HandleUnknownConstraint_UnknownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last constraint is incomplete..
        /// </summary>
        internal static string ConstraintParser_Parse_ConstraintIncomplete {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_ConstraintIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint string contains an empty constraint..
        /// </summary>
        internal static string ConstraintParser_Parse_EmptyConstraint {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_EmptyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0}&apos; after parameter value..
        /// </summary>
        internal static string ConstraintParser_Parse_InvalidCharAfterParam {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_InvalidCharAfterParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0}&apos; after parameters..
        /// </summary>
        internal static string ConstraintParser_Parse_InvalidCharAfterParams {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_InvalidCharAfterParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0}&apos; in constraint name..
        /// </summary>
        internal static string ConstraintParser_Parse_InvalidCharInName {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_InvalidCharInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid character &apos;{0}&apos; in parameters..
        /// </summary>
        internal static string ConstraintParser_Parse_InvalidCharInParameters {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_InvalidCharInParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data outside of constraints at position {0}..
        /// </summary>
        internal static string ConstraintParser_Parse_InvalidContent {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_InvalidContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one parameter of constraint [{0}] is invalid..
        /// </summary>
        internal static string ConstraintParser_Parse_ParametersInvalid {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_ParametersInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmasked character &apos;{0}&apos; in parameter value..
        /// </summary>
        internal static string ConstraintParser_Parse_UnmaskedChar {
            get {
                return ResourceManager.GetString("ConstraintParser_Parse_UnmaskedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot parse constraint string..
        /// </summary>
        internal static string ConstraintParserException_Message {
            get {
                return ResourceManager.GetString("ConstraintParserException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the specified parameter strings is null or empty or contains only white-space..
        /// </summary>
        internal static string DisplayHintConstraint_CheckParameters_InvalidParameter {
            get {
                return ResourceManager.GetString("DisplayHintConstraint_CheckParameters_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list of parameters is empty..
        /// </summary>
        internal static string DisplayHintConstraint_CheckParameters_NoParameter {
            get {
                return ResourceManager.GetString("DisplayHintConstraint_CheckParameters_NoParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: &apos;{1}&apos; is not a valid IP endpoint, host name is invalid..
        /// </summary>
        internal static string EndpointConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("EndpointConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: &apos;{1}&apos; is not a valid IP endpoint, port number is invalid..
        /// </summary>
        internal static string EndpointConstraint_Validate_FailedPort {
            get {
                return ResourceManager.GetString("EndpointConstraint_Validate_FailedPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has one or more flags that are not defined or not valid for this parameter..
        /// </summary>
        internal static string EnumConstraint_Validate_InvalidFlag {
            get {
                return ResourceManager.GetString("EnumConstraint_Validate_InvalidFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: value &apos;{1}&apos; is not defined in enumeration, or not valid for this parameter..
        /// </summary>
        internal static string EnumConstraint_Validate_NotDefined {
            get {
                return ResourceManager.GetString("EnumConstraint_Validate_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: value type &apos;{1}&apos; is not supported by enumeration..
        /// </summary>
        internal static string EnumConstraint_Validate_NotSupported {
            get {
                return ResourceManager.GetString("EnumConstraint_Validate_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration type of {0} (&apos;{1}&apos;) does not match expected enumeration type (&apos;{2}&apos;)..
        /// </summary>
        internal static string EnumTypeConstraint_Validate_WrongEnum {
            get {
                return ResourceManager.GetString("EnumTypeConstraint_Validate_WrongEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized EnumValuesConstraint has an enumeration value key missing..
        /// </summary>
        internal static string EnumValuesConstraint_ctor_KeyMissing {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_ctor_KeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized EnumValuesConstraint contains no UnderlyingDataType property..
        /// </summary>
        internal static string EnumValuesConstraint_ctor_NoUnderlyingDataType {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_ctor_NoUnderlyingDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized EnumValuesConstraint has an enumeration value value missing..
        /// </summary>
        internal static string EnumValuesConstraint_ctor_ValueMissing {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_ctor_ValueMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine underlying data type..
        /// </summary>
        internal static string EnumValuesConstraint_GetParameters_DataType {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_GetParameters_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; does not match underlying data type {1} of the enumeration and cannot be converted into this type..
        /// </summary>
        internal static string EnumValuesConstraint_InvalidValueType {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_InvalidValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type is not one of the integer types..
        /// </summary>
        internal static string EnumValuesConstraint_NotInteger {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_NotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not a valid hexadecimal value..
        /// </summary>
        internal static string EnumValuesConstraint_SetParameters_InvalidHex {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_SetParameters_InvalidHex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is not a valid key/value pair of format &apos;Name=Value&apos;..
        /// </summary>
        internal static string EnumValuesConstraint_SetParameters_InvalidValue {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_SetParameters_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First parameter is not a valid value of the ParameterDataType enumeration..
        /// </summary>
        internal static string EnumValuesConstraint_SetParameters_NotDataType {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_SetParameters_NotDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enumeration values specified for the {0} constraint..
        /// </summary>
        internal static string EnumValuesConstraint_SetParameters_NoValues {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_SetParameters_NoValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint is not sufficiently configured..
        /// </summary>
        internal static string EnumValuesConstraint_Validate_NotConfigured {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_Validate_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine underlying data type of enumeration value..
        /// </summary>
        internal static string EnumValuesConstraint_Validate_ValueType {
            get {
                return ResourceManager.GetString("EnumValuesConstraint_Validate_ValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains at least one character not allowed in a file name. Actual value: &apos;{1}&apos;.
        /// </summary>
        internal static string FileNameConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("FileNameConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type is not supported by the {0} constraint..
        /// </summary>
        internal static string Global_CheckDataType_NotSupported {
            get {
                return ResourceManager.GetString("Global_CheckDataType_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter data type &apos;{0}&apos; cannot be converted into alternative comparison data type &apos;{1}&apos;..
        /// </summary>
        internal static string Global_CheckValueType_AltNotConvertible {
            get {
                return ResourceManager.GetString("Global_CheckValueType_AltNotConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter data type &apos;{0}&apos; cannot be converted into expected data type &apos;{1}&apos;..
        /// </summary>
        internal static string Global_CheckValueType_NotConvertible {
            get {
                return ResourceManager.GetString("Global_CheckValueType_NotConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type may not be &apos;None&apos;..
        /// </summary>
        internal static string Global_ParameterDataType_None {
            get {
                return ResourceManager.GetString("Global_ParameterDataType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter for constraint {0} is invalid..
        /// </summary>
        internal static string Global_SetParameters_Invalid {
            get {
                return ResourceManager.GetString("Global_SetParameters_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of constraint parameters. Constraint {0} requires {1} parameter(s)..
        /// </summary>
        internal static string Global_SetParameters_InvalidCount {
            get {
                return ResourceManager.GetString("Global_SetParameters_InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of constraint parameters. Constraint {0} requires {1} to {2} parameter(s)..
        /// </summary>
        internal static string Global_SetParameters_InvalidCountVariable {
            get {
                return ResourceManager.GetString("Global_SetParameters_InvalidCountVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of constraint parameters. Constraint {0} requires at least {1} parameter(s)..
        /// </summary>
        internal static string Global_SetParameters_InvalidMinCount {
            get {
                return ResourceManager.GetString("Global_SetParameters_InvalidMinCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine underlying data type of enumeration &apos;{0}&apos;..
        /// </summary>
        internal static string Global_UnknownEnumType {
            get {
                return ResourceManager.GetString("Global_UnknownEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value is not of type System.String..
        /// </summary>
        internal static string Global_Validate_NotString {
            get {
                return ResourceManager.GetString("Global_Validate_NotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is empty or contains only white-space..
        /// </summary>
        internal static string Global_Validate_StringEmpty {
            get {
                return ResourceManager.GetString("Global_Validate_StringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; cannot be validated by the {1} constraint..
        /// </summary>
        internal static string Global_Validate_TypeMismatch {
            get {
                return ResourceManager.GetString("Global_Validate_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot  compare data type &apos;{0}&apos; to data type &apos;{1}&apos;, and no conversion to a comparable data type exists..
        /// </summary>
        internal static string Global_Validate_TypeNotConvertible {
            get {
                return ResourceManager.GetString("Global_Validate_TypeNotConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid host name or IP address. Actual value: &apos;{1}&apos;.
        /// </summary>
        internal static string HostNameConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("HostNameConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized InvalidDataTypeException contains no ParameterDataType property..
        /// </summary>
        internal static string InvalidDataTypeException_ctor_DataTypeNull {
            get {
                return ResourceManager.GetString("InvalidDataTypeException_ctor_DataTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type &apos;{1}&apos; is not supported by constraint &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidDataTypeException_Message {
            get {
                return ResourceManager.GetString("InvalidDataTypeException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data type is not supported..
        /// </summary>
        internal static string InvalidDataTypeException_MessageDefault {
            get {
                return ResourceManager.GetString("InvalidDataTypeException_MessageDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length may not be negative..
        /// </summary>
        internal static string LengthConstraint_LengthNegative {
            get {
                return ResourceManager.GetString("LengthConstraint_LengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} byte(s) in length. Current length: {2} byte(s)..
        /// </summary>
        internal static string LengthConstraint_Validate_FailedBytes {
            get {
                return ResourceManager.GetString("LengthConstraint_Validate_FailedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {1} character(s) in length. Current length: {2} character(s)..
        /// </summary>
        internal static string LengthConstraint_Validate_FailedString {
            get {
                return ResourceManager.GetString("LengthConstraint_Validate_FailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains at least one upper-case character..
        /// </summary>
        internal static string LowercaseConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("LowercaseConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length may not be negative..
        /// </summary>
        internal static string MaximumLengthConstraint_LengthNegative {
            get {
                return ResourceManager.GetString("MaximumLengthConstraint_LengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be longer than {1} byte(s). Current length: {2} byte(s)..
        /// </summary>
        internal static string MaximumLengthConstraint_Validate_FailedBytes {
            get {
                return ResourceManager.GetString("MaximumLengthConstraint_Validate_FailedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be longer than {1} character(s). Current length: {2} character(s)..
        /// </summary>
        internal static string MaximumLengthConstraint_Validate_FailedString {
            get {
                return ResourceManager.GetString("MaximumLengthConstraint_Validate_FailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized MaximumValuesConstraint has no MaximumValue property..
        /// </summary>
        internal static string MaximumValueConstraint_ctor_MaximumValue {
            get {
                return ResourceManager.GetString("MaximumValueConstraint_ctor_MaximumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be greater than &apos;{1}&apos;. Actual value: &apos;{2}&apos;..
        /// </summary>
        internal static string MaximumValueConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("MaximumValueConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized MaximumValuesConstraint has no DataType property..
        /// </summary>
        internal static string MaximumValuesConstraint_ctor_DataType {
            get {
                return ResourceManager.GetString("MaximumValuesConstraint_ctor_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length may not be negative..
        /// </summary>
        internal static string MinimumLengthConstraint_LengthNegative {
            get {
                return ResourceManager.GetString("MinimumLengthConstraint_LengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} byte(s) long. Current length: {2} byte(s)..
        /// </summary>
        internal static string MinimumLengthConstraint_Validate_FailedBytes {
            get {
                return ResourceManager.GetString("MinimumLengthConstraint_Validate_FailedBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be at least {1} character(s) long. Current length: {2} character(s)..
        /// </summary>
        internal static string MinimumLengthConstraint_Validate_FailedString {
            get {
                return ResourceManager.GetString("MinimumLengthConstraint_Validate_FailedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized MinimumValuesConstraint has no DataType property..
        /// </summary>
        internal static string MinimumValueConstraint_ctor_DataType {
            get {
                return ResourceManager.GetString("MinimumValueConstraint_ctor_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized MinimumValuesConstraint has no MinimumValue property..
        /// </summary>
        internal static string MinimumValueConstraint_ctor_MinimumValue {
            get {
                return ResourceManager.GetString("MinimumValueConstraint_ctor_MinimumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be less than &apos;{1}&apos;. Actual value: &apos;{2}&apos;..
        /// </summary>
        internal static string MinimumValueConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("MinimumValueConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized ParameterConversionException contains no ActualValue type..
        /// </summary>
        internal static string ParameterConversionException_ctor_ActualTypeNull {
            get {
                return ResourceManager.GetString("ParameterConversionException_ctor_ActualTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized ParameterConversionException contains no ParameterDataType property..
        /// </summary>
        internal static string ParameterConversionException_ctor_DataTypeNull {
            get {
                return ResourceManager.GetString("ParameterConversionException_ctor_DataTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter conversion failed..
        /// </summary>
        internal static string ParameterConversionException_Message {
            get {
                return ResourceManager.GetString("ParameterConversionException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get assembly strong name key..
        /// </summary>
        internal static string ParameterConvert_AES_NoAssemblyName {
            get {
                return ResourceManager.GetString("ParameterConvert_AES_NoAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot decrypt parameter data..
        /// </summary>
        internal static string ParameterConvert_Decrypt_Failed {
            get {
                return ResourceManager.GetString("ParameterConvert_Decrypt_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot encrypt parameter data..
        /// </summary>
        internal static string ParameterConvert_Encrypt_Failed {
            get {
                return ResourceManager.GetString("ParameterConvert_Encrypt_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve values of enumeration &apos;{0}&apos;..
        /// </summary>
        internal static string ParameterConvert_ExamineEnumeration_NoFieldValue {
            get {
                return ResourceManager.GetString("ParameterConvert_ExamineEnumeration_NoFieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an enumeration..
        /// </summary>
        internal static string ParameterConvert_ExamineEnumeration_NotEnum {
            get {
                return ResourceManager.GetString("ParameterConvert_ExamineEnumeration_NotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize XML data into an object of type &apos;{0}&apos;..
        /// </summary>
        internal static string ParameterConvert_FromXml_Failed {
            get {
                return ResourceManager.GetString("ParameterConvert_FromXml_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML deserialization returned no object..
        /// </summary>
        internal static string ParameterConvert_FromXml_NoObjectDeserialized {
            get {
                return ResourceManager.GetString("ParameterConvert_FromXml_NoObjectDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type {0} is not supported by parameter validation..
        /// </summary>
        internal static string ParameterConvert_NetToParameterDataType_NoMatch {
            get {
                return ResourceManager.GetString("ParameterConvert_NetToParameterDataType_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter data type {0} cannot be matched to a .NET data type..
        /// </summary>
        internal static string ParameterConvert_ParameterToNetDataType_NoMatch {
            get {
                return ResourceManager.GetString("ParameterConvert_ParameterToNetDataType_NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ParameterConvert_To_DataTypeNotSupported {
            get {
                return ResourceManager.GetString("ParameterConvert_To_DataTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert string &apos;{0}&apos; to data type &apos;{1}&apos;..
        /// </summary>
        internal static string ParameterConvert_To_Failed {
            get {
                return ResourceManager.GetString("ParameterConvert_To_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a &apos;Type&apos; constraint to determine the target data type..
        /// </summary>
        internal static string ParameterConvert_ToDataType_NoTypeConstraint {
            get {
                return ResourceManager.GetString("ParameterConvert_ToDataType_NoTypeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot resolve type &apos;{0}&apos; from &apos;Type&apos; constraint..
        /// </summary>
        internal static string ParameterConvert_ToDataType_ResolveFailed {
            get {
                return ResourceManager.GetString("ParameterConvert_ToDataType_ResolveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null, but has no NullConstraint that allows it to be null..
        /// </summary>
        internal static string ParameterConvert_ToDataType_ValueNull {
            get {
                return ResourceManager.GetString("ParameterConvert_ToDataType_ValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert string &apos;{0}&apos; to enumeration of type &apos;{1}&apos;..
        /// </summary>
        internal static string ParameterConvert_ToEnumeration_Failed {
            get {
                return ResourceManager.GetString("ParameterConvert_ToEnumeration_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not an enumeration..
        /// </summary>
        internal static string ParameterConvert_ToEnumeration_NotEnum {
            get {
                return ResourceManager.GetString("ParameterConvert_ToEnumeration_NotEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object data type &apos;{0}&apos; does not match parameter data type &apos;{1}&apos;..
        /// </summary>
        internal static string ParameterConvert_ToString_TypeMismatch {
            get {
                return ResourceManager.GetString("ParameterConvert_ToString_TypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot serialize parameter of type &apos;{0}&apos;..
        /// </summary>
        internal static string ParameterConvert_ToXml_Failed {
            get {
                return ResourceManager.GetString("ParameterConvert_ToXml_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter validation failed..
        /// </summary>
        internal static string ParameterValidationException_Message {
            get {
                return ResourceManager.GetString("ParameterValidationException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No validation error..
        /// </summary>
        internal static string ParameterValidationResult_Success {
            get {
                return ResourceManager.GetString("ParameterValidationResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be null..
        /// </summary>
        internal static string ParameterValidator_Validate_ValueNull {
            get {
                return ResourceManager.GetString("ParameterValidator_Validate_ValueNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains at least one character not allowed in a file or directory path. Actual value: &apos;{1}&apos;.
        /// </summary>
        internal static string PathConstraint_Validate_FailedChars {
            get {
                return ResourceManager.GetString("PathConstraint_Validate_FailedChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized RegexConstraint has no Options property..
        /// </summary>
        internal static string RegexConstraint_ctor_NoOptions {
            get {
                return ResourceManager.GetString("RegexConstraint_ctor_NoOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized RegexConstraint has no RegularExpression property..
        /// </summary>
        internal static string RegexConstraint_ctor_NoRegex {
            get {
                return ResourceManager.GetString("RegexConstraint_ctor_NoRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot determine Regex options..
        /// </summary>
        internal static string RegexConstraint_GetParameters_Options {
            get {
                return ResourceManager.GetString("RegexConstraint_GetParameters_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The options are not valid..
        /// </summary>
        internal static string RegexConstraint_OptionsInvalid {
            get {
                return ResourceManager.GetString("RegexConstraint_OptionsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The regular expression pattern is not valid..
        /// </summary>
        internal static string RegexConstraint_PatternInvalid {
            get {
                return ResourceManager.GetString("RegexConstraint_PatternInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not match regular expression &apos;{1}&apos;..
        /// </summary>
        internal static string RegexConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("RegexConstraint_Validate_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized StepConstraint has no DataType property..
        /// </summary>
        internal static string StepConstraint_ctor_DataType {
            get {
                return ResourceManager.GetString("StepConstraint_ctor_DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized StepConstraint has no StepSize property..
        /// </summary>
        internal static string StepConstraint_ctor_StepSize {
            get {
                return ResourceManager.GetString("StepConstraint_ctor_StepSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized TypeConstraint has no TypeName property..
        /// </summary>
        internal static string TypeConstraint_ctor_TypeName {
            get {
                return ResourceManager.GetString("TypeConstraint_ctor_TypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} contains at least one lower-case character..
        /// </summary>
        internal static string UppercaseConstraint_Validate_Failed {
            get {
                return ResourceManager.GetString("UppercaseConstraint_Validate_Failed", resourceCulture);
            }
        }
    }
}
